/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica2.gui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Massielle Coti
 */
public class Granja extends javax.swing.JFrame {
    private int y=3;
    

    FondoPanel fondo = new FondoPanel();
    public Granja() {
        this.setContentPane(fondo);
        initComponents();
        setLocationRelativeTo(null);
        cuadriculaButton1.setVisible(false);
        cuadriculaButton2.setVisible(false);
        cuadriculaButton3.setVisible(false);
        cuadriculaButton4.setVisible(false);
        cuadriculaButton5.setVisible(false);
        cuadriculaButton6.setVisible(false);
        cuadriculaButton7.setVisible(false);
        cuadriculaButton8.setVisible(false);
        cuadriculaButton9.setVisible(false);
        cuadriculaButton10.setVisible(false);
        cuadriculaButton11.setVisible(false);
        cuadriculaButton12.setVisible(false);
        cuadriculaButton13.setVisible(false);
        cuadriculaButton14.setVisible(false);
        cuadriculaButton15.setVisible(false);
        cuadriculaButton16.setVisible(false);
        cuadriculaButton17.setVisible(false);
        cuadriculaButton18.setVisible(false);
        cuadriculaButton19.setVisible(false);
        cuadriculaButton20.setVisible(false);
        cuadriculaButton21.setVisible(false);
        cuadriculaButton22.setVisible(false);
        cuadriculaButton23.setVisible(false);
        cuadriculaButton24.setVisible(false);
        cuadriculaButton25.setVisible(false);
    }

    /*** This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regresarButton = new javax.swing.JButton();
        generarButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cuadriculaButton1 = new javax.swing.JButton();
        cuadriculaButton2 = new javax.swing.JButton();
        cuadriculaButton3 = new javax.swing.JButton();
        cuadriculaButton4 = new javax.swing.JButton();
        cuadriculaButton5 = new javax.swing.JButton();
        cuadriculaButton6 = new javax.swing.JButton();
        cuadriculaButton7 = new javax.swing.JButton();
        cuadriculaButton8 = new javax.swing.JButton();
        cuadriculaButton9 = new javax.swing.JButton();
        cuadriculaButton10 = new javax.swing.JButton();
        cuadriculaButton11 = new javax.swing.JButton();
        cuadriculaButton12 = new javax.swing.JButton();
        cuadriculaButton13 = new javax.swing.JButton();
        cuadriculaButton14 = new javax.swing.JButton();
        cuadriculaButton15 = new javax.swing.JButton();
        cuadriculaButton16 = new javax.swing.JButton();
        cuadriculaButton17 = new javax.swing.JButton();
        cuadriculaButton18 = new javax.swing.JButton();
        cuadriculaButton19 = new javax.swing.JButton();
        cuadriculaButton20 = new javax.swing.JButton();
        cuadriculaButton21 = new javax.swing.JButton();
        cuadriculaButton22 = new javax.swing.JButton();
        cuadriculaButton23 = new javax.swing.JButton();
        cuadriculaButton24 = new javax.swing.JButton();
        cuadriculaButton25 = new javax.swing.JButton();
        botonprueba = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TU GRANJA");

        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });

        generarButton.setText("Generar");
        generarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cuadriculaButton1.setText("jButton3");
        cuadriculaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton1ActionPerformed(evt);
            }
        });

        cuadriculaButton2.setText("jButton4");
        cuadriculaButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton2ActionPerformed(evt);
            }
        });

        cuadriculaButton3.setText("jButton5");
        cuadriculaButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton3ActionPerformed(evt);
            }
        });

        cuadriculaButton4.setText("jButton6");
        cuadriculaButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton4ActionPerformed(evt);
            }
        });

        cuadriculaButton5.setText("jButton7");
        cuadriculaButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton5ActionPerformed(evt);
            }
        });

        cuadriculaButton6.setText("jButton3");
        cuadriculaButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton6ActionPerformed(evt);
            }
        });

        cuadriculaButton7.setText("jButton4");
        cuadriculaButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton7ActionPerformed(evt);
            }
        });

        cuadriculaButton8.setText("jButton5");
        cuadriculaButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton8ActionPerformed(evt);
            }
        });

        cuadriculaButton9.setText("jButton6");
        cuadriculaButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton9ActionPerformed(evt);
            }
        });

        cuadriculaButton10.setText("jButton7");
        cuadriculaButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton10ActionPerformed(evt);
            }
        });

        cuadriculaButton11.setText("jButton3");
        cuadriculaButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton11ActionPerformed(evt);
            }
        });

        cuadriculaButton12.setText("jButton4");
        cuadriculaButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton12ActionPerformed(evt);
            }
        });

        cuadriculaButton13.setText("jButton5");
        cuadriculaButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton13ActionPerformed(evt);
            }
        });

        cuadriculaButton14.setText("jButton6");
        cuadriculaButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton14ActionPerformed(evt);
            }
        });

        cuadriculaButton15.setText("jButton7");
        cuadriculaButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton15ActionPerformed(evt);
            }
        });

        cuadriculaButton16.setText("jButton3");
        cuadriculaButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton16ActionPerformed(evt);
            }
        });

        cuadriculaButton17.setText("jButton4");
        cuadriculaButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton17ActionPerformed(evt);
            }
        });

        cuadriculaButton18.setText("jButton5");
        cuadriculaButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton18ActionPerformed(evt);
            }
        });

        cuadriculaButton19.setText("jButton6");
        cuadriculaButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton19ActionPerformed(evt);
            }
        });

        cuadriculaButton20.setText("jButton7");
        cuadriculaButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton20ActionPerformed(evt);
            }
        });

        cuadriculaButton21.setText("jButton3");
        cuadriculaButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton21ActionPerformed(evt);
            }
        });

        cuadriculaButton22.setText("jButton4");
        cuadriculaButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton22ActionPerformed(evt);
            }
        });

        cuadriculaButton23.setText("jButton5");
        cuadriculaButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton23ActionPerformed(evt);
            }
        });

        cuadriculaButton24.setText("jButton6");
        cuadriculaButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton24ActionPerformed(evt);
            }
        });

        cuadriculaButton25.setText("jButton7");
        cuadriculaButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadriculaButton25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cuadriculaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cuadriculaButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cuadriculaButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cuadriculaButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cuadriculaButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadriculaButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadriculaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadriculaButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadriculaButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadriculaButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadriculaButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadriculaButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonprueba.setText("jButton1");
        botonprueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonpruebaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generarButton)
                    .addComponent(regresarButton))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(botonprueba)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(botonprueba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(generarButton)
                .addGap(18, 18, 18)
                .addComponent(regresarButton)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        this.setVisible(false);
        MenuPrincipal Regresar = new MenuPrincipal();
        Regresar.setVisible(true);
    }//GEN-LAST:event_regresarButtonActionPerformed

    private void generarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarButtonActionPerformed
    
//un random de letras y meterlos en el texto del boton
        
        y = (int) (Math.random() * 100 + 1);
        botonprueba.setText(" "+y);
        if (y>=1&y<=40) {
            cuadriculaButton2.setText("grama");
        }
        if (y>=41&y<=75) {
            cuadriculaButton2.setText("agua");
        }
        if (y>=75&y<=100) {
            cuadriculaButton2.setText("desierto");
        }
        cuadriculaButton1.setText("hola ");
        cuadriculaButton1.setVisible(true);
       
        cuadriculaButton2.setVisible(true);
        cuadriculaButton3.setText("Agua");
        cuadriculaButton3.setVisible(true);
        cuadriculaButton4.setText("Agua");
        cuadriculaButton4.setVisible(true);
        cuadriculaButton5.setText("Agua");
        cuadriculaButton5.setVisible(true);
    }//GEN-LAST:event_generarButtonActionPerformed

    private void cuadriculaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton1ActionPerformed

    private void cuadriculaButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton2ActionPerformed

    private void cuadriculaButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton3ActionPerformed

    private void cuadriculaButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton4ActionPerformed

    private void cuadriculaButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton5ActionPerformed

    private void cuadriculaButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton6ActionPerformed

    private void cuadriculaButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton7ActionPerformed

    private void cuadriculaButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton8ActionPerformed

    private void cuadriculaButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton9ActionPerformed

    private void cuadriculaButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton10ActionPerformed

    private void cuadriculaButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton11ActionPerformed

    private void cuadriculaButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton12ActionPerformed

    private void cuadriculaButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton13ActionPerformed

    private void cuadriculaButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton14ActionPerformed

    private void cuadriculaButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton15ActionPerformed

    private void cuadriculaButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton16ActionPerformed

    private void cuadriculaButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton17ActionPerformed

    private void cuadriculaButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton18ActionPerformed

    private void cuadriculaButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton19ActionPerformed

    private void cuadriculaButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton20ActionPerformed

    private void cuadriculaButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton21ActionPerformed

    private void cuadriculaButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton22ActionPerformed

    private void cuadriculaButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton23ActionPerformed

    private void cuadriculaButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton24ActionPerformed

    private void cuadriculaButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadriculaButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadriculaButton25ActionPerformed

    private void botonpruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonpruebaActionPerformed
        
    }//GEN-LAST:event_botonpruebaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonprueba;
    private javax.swing.JButton cuadriculaButton1;
    private javax.swing.JButton cuadriculaButton10;
    private javax.swing.JButton cuadriculaButton11;
    private javax.swing.JButton cuadriculaButton12;
    private javax.swing.JButton cuadriculaButton13;
    private javax.swing.JButton cuadriculaButton14;
    private javax.swing.JButton cuadriculaButton15;
    private javax.swing.JButton cuadriculaButton16;
    private javax.swing.JButton cuadriculaButton17;
    private javax.swing.JButton cuadriculaButton18;
    private javax.swing.JButton cuadriculaButton19;
    private javax.swing.JButton cuadriculaButton2;
    private javax.swing.JButton cuadriculaButton20;
    private javax.swing.JButton cuadriculaButton21;
    private javax.swing.JButton cuadriculaButton22;
    private javax.swing.JButton cuadriculaButton23;
    private javax.swing.JButton cuadriculaButton24;
    private javax.swing.JButton cuadriculaButton25;
    private javax.swing.JButton cuadriculaButton3;
    private javax.swing.JButton cuadriculaButton4;
    private javax.swing.JButton cuadriculaButton5;
    private javax.swing.JButton cuadriculaButton6;
    private javax.swing.JButton cuadriculaButton7;
    private javax.swing.JButton cuadriculaButton8;
    private javax.swing.JButton cuadriculaButton9;
    private javax.swing.JButton generarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regresarButton;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel{
    private Image imagen;
    @Override
    public void paint(Graphics g){
    imagen = new ImageIcon(getClass().getResource("/practica2imagenes/granja.jpg")).getImage();
    g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
    setOpaque(false);
    super.paint(g);
        }
    }

}
